# frozen_string_literal: true

source "https://rubygems.org"

gem "allure-cucumber", "2.16.1"
gem "cucumber", " 7.1"
gem "capybara", "3.36"
gem "selenium-webdriver", " 4.1"
gem "rspec", "3.10"
gem "faker", "2.19"
gem "mongo", "2.13.1"
gem "webdrivers", "~> 4.0", require: false
gem "httparty", "0.20.0"
